### ISSUE TITLE
MDP Input currecnt song not send

### ISSUE THREAD

**Issue by akarnaukh** [cinhcet/node-red-contrib-mpd#7]
If send command to MPD over MPD Output node, MPD Input node not returned in msg.payload.currentsong and the status of the server in msg.payload.status. 
If the status changes have occurred in the player itself, then everything is OK.

**Comment by cinhcet** [comment]
Three things:
1. Sometimes mpd just does not send updates, don't know why. I think that this is not something I can fix in this node.
2. Normally, the status update should come a few seconds later, is this the case for you?
3. Could you try to install a previous version of this node, since I recently changed something, just to make sure that this has not changed anything:
npm install node-red-contrib-mpd@1.2.3

A workaround is query the state manually each time you interact with the server, this can be done for example by sending a "currentsong" payload into the output node.

**Comment by akarnaukh** [comment]
I checked all version.
The status comes at once if the sommand is sent for example via mpc.
I just found out. This only happens if the command contains command_list_begin.
For example:
var func = msg.payload;
msg.payload = "command_list_begin\r\npause\r\n"+func+"\r\ncommand_list_end\r\n";
return msg;

**Comment by akarnaukh** [comment]
Apparently this is a feature of the MPD
Thank you for your prompt response
